name: Auto approve
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'release/**'
      - 'backport/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
