name: Create Release Pull Request
on: [workflow_dispatch]
jobs:
  createReleasePullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d@%H_%M')"

      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Reset develop branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop

      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.RELEASE_SLAYER_APP_SECRET }}
          APP_ID: ${{ secrets.RELEASE_SLAYER_APP_ID }}

      - name: Get App Installation Token
        run: |
          echo "This token is masked: ${TOKEN}"
        env:
          TOKEN: ${{ steps.get_token.outputs.app_token }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: release/${{ steps.date.outputs.date }}
          title: 'New Release ${{ steps.date.outputs.date }}'
          body: |
            This PR was made with ❤️ by the create-pull-request action 💪
          draft: false
          token: ${{ steps.get_token.outputs.app_token }}

      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
