name: PR Labeler
on: [pull_request]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.RELEASE_SLAYER_APP_ID }}
          private_key: ${{ secrets.RELEASE_SLAYER_APP_SECRET }}

      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
